export { createWebAudioEngine, musoAudioEngine } from "./createWebAudioEngine";
export {
  createLookaheadScheduler,
  type LookaheadScheduler,
  type LookaheadSchedulerEvent,
  type LookaheadSchedulerOptions,
} from "./lookaheadScheduler";
export {
  exercisePlaybackRequestsAreEqual,
  exercisePlaybackCoordinator,
  isExercisePlaybackActive,
  type ExercisePlaybackEvent,
  type ExercisePlaybackRequest,
  type ExercisePlaybackSnapshot,
} from "./exercisePlaybackCoordinator";
export {
  ExerciseAuditionController,
  type ExerciseAuditionAudioEngine,
  type ExerciseAuditionNote,
  type ExerciseAuditionRequest,
} from "./exerciseAuditionController";
export {
  DEFAULT_CONCERT_PITCH_HZ,
  MIDI_A4,
  MIDI_MAX,
  MIDI_MIN,
  MUSICAL_SURFACE_MIDI_MAX,
  MUSICAL_SURFACE_MIDI_MIN,
  isMusicalSurfaceMidiNote,
  isPlayableMidiNote,
  midiToFrequency,
} from "./pitch";
export {
  audioPresets,
  defaultAudioPresetIds,
  getAudioPresetsForSurface,
  getDefaultAudioPresetId,
  isAudioPresetId,
  isAudioPresetAvailableOn,
  resolveAudioPreset,
} from "./presets";
export {
  DEFAULT_MASTER_AMBIENCE_PRESET_ID,
  getMasterAmbiencePreset,
  isMasterAmbiencePresetId,
  masterAmbiencePresets,
  resolveMasterAmbiencePresetId,
} from "./masterAmbience";
export type {
  AudioEngine,
  AudioEffectConfig,
  AudioPreset,
  AudioPresetFamily,
  AudioPresetId,
  AudioPresetSurface,
  AudioUse,
  AudioVoiceHandle,
  AudioClockSnapshot,
  ChorusEffectConfig,
  DelayEffectConfig,
  DroneHandle,
  DroneNoteRequest,
  DroneRequest,
  DistortionConfig,
  DistortionEffectConfig,
  EnvelopeConfig,
  HarmonicPartialConfig,
  HarmonicVoiceConfig,
  LowPitchAssistConfig,
  MasterAmbienceEffectConfig,
  MasterAmbiencePreset,
  MasterAmbiencePresetId,
  PlayNoteRequest,
  PlaybackGroupHandle,
  PitchGainConfig,
  ReverbEffectConfig,
  ScheduleMetronomeClickRequest,
  ScheduleNoteRequest,
  UnisonConfig,
  VoiceInsertEffectConfig,
} from "./types";
